"""empty message

Revision ID: 9518100c6375
Revises: d94bf8b53652
Create Date: 2016-06-15 21:54:57.205765

"""

# revision identifiers, used by Alembic.
revision = '9518100c6375'
down_revision = 'd94bf8b53652'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', postgresql.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['api_key'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'api_key')
    ### end Alembic commands ###
