"""empty message

Revision ID: d94bf8b53652
Revises: df5eb67e09f4
Create Date: 2016-06-10 18:04:33.491425

"""

# revision identifiers, used by Alembic.
revision = 'd94bf8b53652'
down_revision = 'df5eb67e09f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('registered_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('sms_verified_on', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_verified_on')
    op.drop_column('users', 'registered_on')
    op.drop_column('users', 'email_verified_on')
    ### end Alembic commands ###
