"""empty message

Revision ID: df5eb67e09f4
Revises: 08973d51946e
Create Date: 2016-06-09 17:53:20.549970

"""

# revision identifiers, used by Alembic.
revision = 'df5eb67e09f4'
down_revision = '08973d51946e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('users', sa.Column('sms_verified', sa.Boolean(), server_default='f', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_verified')
    op.drop_column('users', 'email_verified')
    ### end Alembic commands ###
